function [varargout] = trann_train_best_performance(varargin)
    %% *SET-UP*
    NNs = varargin{1};
    prf = varargin{2};
    dsg = varargin{3};
    wd  = varargin{4};
    dbn_name = varargin{5};
    verNet = varargin{6};
    

    %% *COMPUTE BEST PERFORMANCE*
    [bst.prf,bst.idx] = min(0.25*prf.vld+0.25*prf.tst+0.25*prf.trn+0.25*prf.r);
    ann = NNs{bst.idx};
    bst.r=prf.r(bst.idx);
    bst.mae=prf.mae(bst.idx);
    prf.avg = mean(prf.vld);
    prf.std = std(prf.vld);

    %% *COMPARE TRAINING*
    %MSE vld and tst
    % set(0,'defaultaxescolororder',[0.65,0.65,0.65;0,0,0;0,0,0;0,0,0]);
    % fpplot('xpl',{(1:dsg.ntr)';(1:dsg.ntr)';[bst.idx;bst.idx];[0.5;dsg.ntr+0.5]},...
    %     'ypl',{prf.vld;prf.tst;[0.01;0.1];[prf.avg;prf.avg]},...
    %     'pfg',[0,0,10,10],'tit',{'ANN-performance'},'scl',{'sly'},...
    %     'xlb',{'ANN-ID'},'xlm',{[0.5;dsg.ntr+0.5]},'xtk',{(1:2:dsg.ntr)},...
    %     'ylb',{'MSE [1]'},'ylm',{[0.01;0.1]},'ytk',{(1:10)./100},...
    %     'lst',{'none';'none';'--';'--'},'lwd',[0.1;0.1;1;2],'mrk',{'o';'s';'none';'none'});
    % saveas(gcf,fullfile(wd,strcat(dsg.fnm,'_all_prf_',dbn_name,'_',verNet)),'jpeg');
    % close(gcf);
    % 
    % %R^2 plot
    %     set(0,'defaultaxescolororder',[0.65,0.65,0.65;0,0,0;0,0,0;0,0,0]);
    % fpplot('xpl',{(1:dsg.ntr)';bst.idx},...
    %     'ypl',{prf.r;bst.r},...
    %     'pfg',[0,0,10,10],'tit',{'ANN-performance'},'scl',{'sly'},...
    %     'xlb',{'ANN-ID'},'xlm',{[0.5;dsg.ntr+0.5]},'xtk',{(1:2:dsg.ntr)},...
    %     'ylb',{'R^2'},'ylm',{[0.7;1]},'ytk',{(7:10)./10},...
    %     'lst',{'none';'none'},'lwd',[0.1;0.1],'mrk',{'o';'x'});
    % saveas(gcf,fullfile(wd,strcat(dsg.fnm,'_all_r_',dbn_name,'_',verNet)),'jpeg');
    % close(gcf);
    % 
    %     %MAE plot
    %     set(0,'defaultaxescolororder',[0.65,0.65,0.65;0,0,0;0,0,0;0,0,0]);
    % fpplot('xpl',{(1:dsg.ntr)';bst.idx},...
    %     'ypl',{prf.mae;bst.mae},...
    %     'pfg',[0,0,10,10],'tit',{'ANN-performance'},'scl',{'sly'},...
    %     'xlb',{'ANN-ID'},'xlm',{[0.5;dsg.ntr+0.5]},'xtk',{(1:2:dsg.ntr)},...
    %     'ylb',{'MAE'},'ylm',{[0.1;0.3]},'ytk',{(1:3)./10},...
    %     'lst',{'none';'none'},'lwd',[0.1;0.1],'mrk',{'o';'x'});
    % saveas(gcf,fullfile(wd,strcat(dsg.fnm,'_all_mae_',dbn_name,'_',verNet)),'jpeg');
    % close(gcf);
    % 
    % % *BEST ANN PERFORMANCE*
    % set(0,'defaultaxescolororder',[0,0,0]);
    % xlm = [ann.trs.TrainingHistory.Iteration(1);ann.trs.TrainingHistory.Iteration(end)];
    % ylm = [1e-1;1e1];
    % fpplot('xpl',{ann.trs.TrainingHistory.Iteration';ann.trs.ValidationHistory.Iteration;...
    %     [ann.trs.OutputNetworkIteration;ann.trs.OutputNetworkIteration];xlm},...
    %     'ypl',{ann.trs.TrainingHistory.Loss';ann.trs.ValidationHistory.Loss';
    %     ylm;...
    %     [ann.trs.ValidationHistory.Loss(ann.trs.ValidationHistory.Iteration==ann.trs.OutputNetworkIteration);...
    %     ann.trs.ValidationHistory.Loss(ann.trs.ValidationHistory.Iteration==ann.trs.OutputNetworkIteration)]},...
    %     'pfg',[0,0,10,10],'tit',{'ANN-performance'},'scl',{'sly'},...
    %     'xlb',{'Epochs'},'xlm',{xlm},'xtk',{(0:20:xlm(end))},'leg',{{'TRAIN';'VALID'}},...
    %     'ylb',{'MSE [1]'},'ylm',{ylm},'ytk',{10.^(-2:1)'},...
    %     'mrk',{'none';'none';'none';'none';'none'},...
    %     'lst',{'-';'--';':';'-';'-'},'lwd',[1;1;1;1;1]);
    % saveas(gcf,fullfile(wd,strcat(dsg.fnm,'_bst_prf_',dbn_name,'_',verNet)),'jpeg');
    % close(gcf);

    %% *OUTPUT*
    varargout{1} = ann;
    return
end
